ARG BASE_IMAGE=vllm/vllm-openai:v0.25.0-cu129-ubuntu2404
FROM ${BASE_IMAGE}

RUN ln -sf /usr/bin/python3 /usr/bin/python

COPY .sandbox/ ./sandbox

RUN cp -r sandbox/overlay/* /usr/local/lib/python3.12/dist-packages/vllm/